package com.techventure.androidext.extEnums

enum class ExtEnums (val key: String) {
    VALID("valid"),
    MSG("msg"),
    FROM_DATE("from_date"),
    TO_DATE("to_date"),
    TEXT_COLOR("text_color"),
    TEXT_BACKGROUND("background"),
    STATUS("status"),
    FROM_DATE_STRING("from_date_string"),
    TO_DATE_STRING("to_date_string"),
    SECONDS("second"),
    MINUTES("minute"),
    HOURS("hour"),
    SIMPLE_TIMER_NOTIFICATION("simple_timer_notification"),
    EXPANDED_TIMER_NOTIFICATION("expanded_timer_notification"),
    STARTED_AT("started_at"),
    START_TRACKING("start_tracking"),
    STOP_TRACKING("stop_tracking"),
    START_BREAK("start_break"),
    STOP_BREAK("stop_break"),
    UPCOMING_LEAVES("upcoming_leaves"),
    TYPE("type"),
    CATEGORY("category"),
    START_DATE("start_date"),
    PAGE("page"),
    SORT("sort"),
    MONTH("month"),
    COLOR("color"),
    CANCEL("cancel"),
    TIME_STRING("timeString"),
    DATE("date"),
}